server:
    port: 7070
#
spring:
    kafka:
        json:
            bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
            producer:
                key-serializer: org.apache.kafka.common.serialization.StringSerializer
                value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
                acks: -1
        string:
            bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
            producer:
                key-serializer: org.apache.kafka.common.serialization.StringSerializer
                value-serializer: org.apache.kafka.common.serialization.StringSerializer
                acks: -1

    datasource:
        url: jdbc:mysql://localhost:33060/campus?serverTimezone=Asia/Seoul
        username: myuser
        password: mypassword
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        properties:
            hibernate:
                show_sql: true
                format_sql: true

# https://springdoc.org/#properties 참조
# https://springdoc.org/#migrating-from-springfox 참조
# 그룹설정(swagger 2 기준 Docket)은 SwaggerConfig 클래스에서 설정
springdoc:
    version: '1.0.0'
    remove-broken-reference-definitions: false # 해당 옵션을 설정하지 않으면 generic 타입 리턴시에 경고 alert 발생됨
    writer-with-default-pretty-printer: true
    #  show-actuator: true
    default-consumes-media-type: "application/json"
    default-produces-media-type: "application/json"
    api-docs:
        version: openapi_3_1
    swagger-ui:
        display-request-duration: true
        groups-order: DESC
        operationsSorter: method
        disable-swagger-default-url: true
        use-root-path: true
        path: /swagger-ui.html
    cache:
        disabled: true
    show-login-endpoint: true
    show-actuator: true